import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-country-flag',
  standalone: true,
  template: `
    @if (isValidCountryCode()) {
      <img 
        class="country-flag" 
        [src]="getCountryFlagUrl(countryCode)" 
        [alt]="getCountryName(countryCode)"
        [title]="getCountryName(countryCode)"
        loading="lazy" />
    }
  `,
  styles: [`
    .country-flag {
      width: 1.2em;
      height: auto;
      margin-right: 0.25rem;
      vertical-align: middle;
      border-radius: 2px;
    }
  `]
})
export class CountryFlagComponent {
  @Input() countryCode: string | null | undefined = null;

  private countries: { [key: string]: { name: string; flag: string } } = {
    'AD': { name: 'Andorra', flag: 'https://flagcdn.com/w20/ad.png' },
    'AE': { name: 'United Arab Emirates', flag: 'https://flagcdn.com/w20/ae.png' },
    'AF': { name: 'Afghanistan', flag: 'https://flagcdn.com/w20/af.png' },
    'AG': { name: 'Antigua and Barbuda', flag: 'https://flagcdn.com/w20/ag.png' },
    'AI': { name: 'Anguilla', flag: 'https://flagcdn.com/w20/ai.png' },
    'AL': { name: 'Albania', flag: 'https://flagcdn.com/w20/al.png' },
    'AM': { name: 'Armenia', flag: 'https://flagcdn.com/w20/am.png' },
    'AO': { name: 'Angola', flag: 'https://flagcdn.com/w20/ao.png' },
    'AQ': { name: 'Antarctica', flag: 'https://flagcdn.com/w20/aq.png' },
    'AR': { name: 'Argentina', flag: 'https://flagcdn.com/w20/ar.png' },
    'AS': { name: 'American Samoa', flag: 'https://flagcdn.com/w20/as.png' },
    'AT': { name: 'Austria', flag: 'https://flagcdn.com/w20/at.png' },
    'AU': { name: 'Australia', flag: 'https://flagcdn.com/w20/au.png' },
    'AW': { name: 'Aruba', flag: 'https://flagcdn.com/w20/aw.png' },
    'AX': { name: 'Åland Islands', flag: 'https://flagcdn.com/w20/ax.png' },
    'AZ': { name: 'Azerbaijan', flag: 'https://flagcdn.com/w20/az.png' },
    'BA': { name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w20/ba.png' },
    'BB': { name: 'Barbados', flag: 'https://flagcdn.com/w20/bb.png' },
    'BD': { name: 'Bangladesh', flag: 'https://flagcdn.com/w20/bd.png' },
    'BE': { name: 'Belgium', flag: 'https://flagcdn.com/w20/be.png' },
    'BF': { name: 'Burkina Faso', flag: 'https://flagcdn.com/w20/bf.png' },
    'BG': { name: 'Bulgaria', flag: 'https://flagcdn.com/w20/bg.png' },
    'BH': { name: 'Bahrain', flag: 'https://flagcdn.com/w20/bh.png' },
    'BI': { name: 'Burundi', flag: 'https://flagcdn.com/w20/bi.png' },
    'BJ': { name: 'Benin', flag: 'https://flagcdn.com/w20/bj.png' },
    'BL': { name: 'Saint Barthélemy', flag: 'https://flagcdn.com/w20/bl.png' },
    'BM': { name: 'Bermuda', flag: 'https://flagcdn.com/w20/bm.png' },
    'BN': { name: 'Brunei', flag: 'https://flagcdn.com/w20/bn.png' },
    'BO': { name: 'Bolivia', flag: 'https://flagcdn.com/w20/bo.png' },
    'BQ': { name: 'Caribbean Netherlands', flag: 'https://flagcdn.com/w20/bq.png' },
    'BR': { name: 'Brazil', flag: 'https://flagcdn.com/w20/br.png' },
    'BS': { name: 'Bahamas', flag: 'https://flagcdn.com/w20/bs.png' },
    'BT': { name: 'Bhutan', flag: 'https://flagcdn.com/w20/bt.png' },
    'BV': { name: 'Bouvet Island', flag: 'https://flagcdn.com/w20/bv.png' },
    'BW': { name: 'Botswana', flag: 'https://flagcdn.com/w20/bw.png' },
    'BY': { name: 'Belarus', flag: 'https://flagcdn.com/w20/by.png' },
    'BZ': { name: 'Belize', flag: 'https://flagcdn.com/w20/bz.png' },
    'CA': { name: 'Canada', flag: 'https://flagcdn.com/w20/ca.png' },
    'CC': { name: 'Cocos (Keeling) Islands', flag: 'https://flagcdn.com/w20/cc.png' },
    'CD': { name: 'Democratic Republic of the Congo', flag: 'https://flagcdn.com/w20/cd.png' },
    'CF': { name: 'Central African Republic', flag: 'https://flagcdn.com/w20/cf.png' },
    'CG': { name: 'Republic of the Congo', flag: 'https://flagcdn.com/w20/cg.png' },
    'CH': { name: 'Switzerland', flag: 'https://flagcdn.com/w20/ch.png' },
    'CI': { name: 'Côte d\'Ivoire', flag: 'https://flagcdn.com/w20/ci.png' },
    'CK': { name: 'Cook Islands', flag: 'https://flagcdn.com/w20/ck.png' },
    'CL': { name: 'Chile', flag: 'https://flagcdn.com/w20/cl.png' },
    'CM': { name: 'Cameroon', flag: 'https://flagcdn.com/w20/cm.png' },
    'CN': { name: 'China', flag: 'https://flagcdn.com/w20/cn.png' },
    'CO': { name: 'Colombia', flag: 'https://flagcdn.com/w20/co.png' },
    'CR': { name: 'Costa Rica', flag: 'https://flagcdn.com/w20/cr.png' },
    'CU': { name: 'Cuba', flag: 'https://flagcdn.com/w20/cu.png' },
    'CV': { name: 'Cape Verde', flag: 'https://flagcdn.com/w20/cv.png' },
    'CW': { name: 'Curaçao', flag: 'https://flagcdn.com/w20/cw.png' },
    'CX': { name: 'Christmas Island', flag: 'https://flagcdn.com/w20/cx.png' },
    'CY': { name: 'Cyprus', flag: 'https://flagcdn.com/w20/cy.png' },
    'CZ': { name: 'Czech Republic', flag: 'https://flagcdn.com/w20/cz.png' },
    'DE': { name: 'Germany', flag: 'https://flagcdn.com/w20/de.png' },
    'DJ': { name: 'Djibouti', flag: 'https://flagcdn.com/w20/dj.png' },
    'DK': { name: 'Denmark', flag: 'https://flagcdn.com/w20/dk.png' },
    'DM': { name: 'Dominica', flag: 'https://flagcdn.com/w20/dm.png' },
    'DO': { name: 'Dominican Republic', flag: 'https://flagcdn.com/w20/do.png' },
    'DZ': { name: 'Algeria', flag: 'https://flagcdn.com/w20/dz.png' },
    'EC': { name: 'Ecuador', flag: 'https://flagcdn.com/w20/ec.png' },
    'EE': { name: 'Estonia', flag: 'https://flagcdn.com/w20/ee.png' },
    'EG': { name: 'Egypt', flag: 'https://flagcdn.com/w20/eg.png' },
    'EH': { name: 'Western Sahara', flag: 'https://flagcdn.com/w20/eh.png' },
    'ER': { name: 'Eritrea', flag: 'https://flagcdn.com/w20/er.png' },
    'ES': { name: 'Spain', flag: 'https://flagcdn.com/w20/es.png' },
    'ET': { name: 'Ethiopia', flag: 'https://flagcdn.com/w20/et.png' },
    'FI': { name: 'Finland', flag: 'https://flagcdn.com/w20/fi.png' },
    'FJ': { name: 'Fiji', flag: 'https://flagcdn.com/w20/fj.png' },
    'FK': { name: 'Falkland Islands', flag: 'https://flagcdn.com/w20/fk.png' },
    'FM': { name: 'Micronesia', flag: 'https://flagcdn.com/w20/fm.png' },
    'FO': { name: 'Faroe Islands', flag: 'https://flagcdn.com/w20/fo.png' },
    'FR': { name: 'France', flag: 'https://flagcdn.com/w20/fr.png' },
    'GA': { name: 'Gabon', flag: 'https://flagcdn.com/w20/ga.png' },
    'GB': { name: 'United Kingdom', flag: 'https://flagcdn.com/w20/gb.png' },
    'GD': { name: 'Grenada', flag: 'https://flagcdn.com/w20/gd.png' },
    'GE': { name: 'Georgia', flag: 'https://flagcdn.com/w20/ge.png' },
    'GF': { name: 'French Guiana', flag: 'https://flagcdn.com/w20/gf.png' },
    'GG': { name: 'Guernsey', flag: 'https://flagcdn.com/w20/gg.png' },
    'GH': { name: 'Ghana', flag: 'https://flagcdn.com/w20/gh.png' },
    'GI': { name: 'Gibraltar', flag: 'https://flagcdn.com/w20/gi.png' },
    'GL': { name: 'Greenland', flag: 'https://flagcdn.com/w20/gl.png' },
    'GM': { name: 'Gambia', flag: 'https://flagcdn.com/w20/gm.png' },
    'GN': { name: 'Guinea', flag: 'https://flagcdn.com/w20/gn.png' },
    'GP': { name: 'Guadeloupe', flag: 'https://flagcdn.com/w20/gp.png' },
    'GQ': { name: 'Equatorial Guinea', flag: 'https://flagcdn.com/w20/gq.png' },
    'GR': { name: 'Greece', flag: 'https://flagcdn.com/w20/gr.png' },
    'GS': { name: 'South Georgia and the South Sandwich Islands', flag: 'https://flagcdn.com/w20/gs.png' },
    'GT': { name: 'Guatemala', flag: 'https://flagcdn.com/w20/gt.png' },
    'GU': { name: 'Guam', flag: 'https://flagcdn.com/w20/gu.png' },
    'GW': { name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w20/gw.png' },
    'GY': { name: 'Guyana', flag: 'https://flagcdn.com/w20/gy.png' },
    'HK': { name: 'Hong Kong', flag: 'https://flagcdn.com/w20/hk.png' },
    'HM': { name: 'Heard Island and McDonald Islands', flag: 'https://flagcdn.com/w20/hm.png' },
    'HN': { name: 'Honduras', flag: 'https://flagcdn.com/w20/hn.png' },
    'HR': { name: 'Croatia', flag: 'https://flagcdn.com/w20/hr.png' },
    'HT': { name: 'Haiti', flag: 'https://flagcdn.com/w20/ht.png' },
    'HU': { name: 'Hungary', flag: 'https://flagcdn.com/w20/hu.png' },
    'ID': { name: 'Indonesia', flag: 'https://flagcdn.com/w20/id.png' },
    'IE': { name: 'Ireland', flag: 'https://flagcdn.com/w20/ie.png' },
    'IL': { name: 'Israel', flag: 'https://flagcdn.com/w20/il.png' },
    'IM': { name: 'Isle of Man', flag: 'https://flagcdn.com/w20/im.png' },
    'IN': { name: 'India', flag: 'https://flagcdn.com/w20/in.png' },
    'IO': { name: 'British Indian Ocean Territory', flag: 'https://flagcdn.com/w20/io.png' },
    'IQ': { name: 'Iraq', flag: 'https://flagcdn.com/w20/iq.png' },
    'IR': { name: 'Iran', flag: 'https://flagcdn.com/w20/ir.png' },
    'IS': { name: 'Iceland', flag: 'https://flagcdn.com/w20/is.png' },
    'IT': { name: 'Italy', flag: 'https://flagcdn.com/w20/it.png' },
    'JE': { name: 'Jersey', flag: 'https://flagcdn.com/w20/je.png' },
    'JM': { name: 'Jamaica', flag: 'https://flagcdn.com/w20/jm.png' },
    'JO': { name: 'Jordan', flag: 'https://flagcdn.com/w20/jo.png' },
    'JP': { name: 'Japan', flag: 'https://flagcdn.com/w20/jp.png' },
    'KE': { name: 'Kenya', flag: 'https://flagcdn.com/w20/ke.png' },
    'KG': { name: 'Kyrgyzstan', flag: 'https://flagcdn.com/w20/kg.png' },
    'KH': { name: 'Cambodia', flag: 'https://flagcdn.com/w20/kh.png' },
    'KI': { name: 'Kiribati', flag: 'https://flagcdn.com/w20/ki.png' },
    'KM': { name: 'Comoros', flag: 'https://flagcdn.com/w20/km.png' },
    'KN': { name: 'Saint Kitts and Nevis', flag: 'https://flagcdn.com/w20/kn.png' },
    'KP': { name: 'North Korea', flag: 'https://flagcdn.com/w20/kp.png' },
    'KR': { name: 'South Korea', flag: 'https://flagcdn.com/w20/kr.png' },
    'KW': { name: 'Kuwait', flag: 'https://flagcdn.com/w20/kw.png' },
    'KY': { name: 'Cayman Islands', flag: 'https://flagcdn.com/w20/ky.png' },
    'KZ': { name: 'Kazakhstan', flag: 'https://flagcdn.com/w20/kz.png' },
    'LA': { name: 'Laos', flag: 'https://flagcdn.com/w20/la.png' },
    'LB': { name: 'Lebanon', flag: 'https://flagcdn.com/w20/lb.png' },
    'LC': { name: 'Saint Lucia', flag: 'https://flagcdn.com/w20/lc.png' },
    'LI': { name: 'Liechtenstein', flag: 'https://flagcdn.com/w20/li.png' },
    'LK': { name: 'Sri Lanka', flag: 'https://flagcdn.com/w20/lk.png' },
    'LR': { name: 'Liberia', flag: 'https://flagcdn.com/w20/lr.png' },
    'LS': { name: 'Lesotho', flag: 'https://flagcdn.com/w20/ls.png' },
    'LT': { name: 'Lithuania', flag: 'https://flagcdn.com/w20/lt.png' },
    'LU': { name: 'Luxembourg', flag: 'https://flagcdn.com/w20/lu.png' },
    'LV': { name: 'Latvia', flag: 'https://flagcdn.com/w20/lv.png' },
    'LY': { name: 'Libya', flag: 'https://flagcdn.com/w20/ly.png' },
    'MA': { name: 'Morocco', flag: 'https://flagcdn.com/w20/ma.png' },
    'MC': { name: 'Monaco', flag: 'https://flagcdn.com/w20/mc.png' },
    'MD': { name: 'Moldova', flag: 'https://flagcdn.com/w20/md.png' },
    'ME': { name: 'Montenegro', flag: 'https://flagcdn.com/w20/me.png' },
    'MF': { name: 'Saint Martin', flag: 'https://flagcdn.com/w20/mf.png' },
    'MG': { name: 'Madagascar', flag: 'https://flagcdn.com/w20/mg.png' },
    'MH': { name: 'Marshall Islands', flag: 'https://flagcdn.com/w20/mh.png' },
    'MK': { name: 'North Macedonia', flag: 'https://flagcdn.com/w20/mk.png' },
    'ML': { name: 'Mali', flag: 'https://flagcdn.com/w20/ml.png' },
    'MM': { name: 'Myanmar', flag: 'https://flagcdn.com/w20/mm.png' },
    'MN': { name: 'Mongolia', flag: 'https://flagcdn.com/w20/mn.png' },
    'MO': { name: 'Macao', flag: 'https://flagcdn.com/w20/mo.png' },
    'MP': { name: 'Northern Mariana Islands', flag: 'https://flagcdn.com/w20/mp.png' },
    'MQ': { name: 'Martinique', flag: 'https://flagcdn.com/w20/mq.png' },
    'MR': { name: 'Mauritania', flag: 'https://flagcdn.com/w20/mr.png' },
    'MS': { name: 'Montserrat', flag: 'https://flagcdn.com/w20/ms.png' },
    'MT': { name: 'Malta', flag: 'https://flagcdn.com/w20/mt.png' },
    'MU': { name: 'Mauritius', flag: 'https://flagcdn.com/w20/mu.png' },
    'MV': { name: 'Maldives', flag: 'https://flagcdn.com/w20/mv.png' },
    'MW': { name: 'Malawi', flag: 'https://flagcdn.com/w20/mw.png' },
    'MX': { name: 'Mexico', flag: 'https://flagcdn.com/w20/mx.png' },
    'MY': { name: 'Malaysia', flag: 'https://flagcdn.com/w20/my.png' },
    'MZ': { name: 'Mozambique', flag: 'https://flagcdn.com/w20/mz.png' },
    'NA': { name: 'Namibia', flag: 'https://flagcdn.com/w20/na.png' },
    'NC': { name: 'New Caledonia', flag: 'https://flagcdn.com/w20/nc.png' },
    'NE': { name: 'Niger', flag: 'https://flagcdn.com/w20/ne.png' },
    'NF': { name: 'Norfolk Island', flag: 'https://flagcdn.com/w20/nf.png' },
    'NG': { name: 'Nigeria', flag: 'https://flagcdn.com/w20/ng.png' },
    'NI': { name: 'Nicaragua', flag: 'https://flagcdn.com/w20/ni.png' },
    'NL': { name: 'Netherlands', flag: 'https://flagcdn.com/w20/nl.png' },
    'NO': { name: 'Norway', flag: 'https://flagcdn.com/w20/no.png' },
    'NP': { name: 'Nepal', flag: 'https://flagcdn.com/w20/np.png' },
    'NR': { name: 'Nauru', flag: 'https://flagcdn.com/w20/nr.png' },
    'NU': { name: 'Niue', flag: 'https://flagcdn.com/w20/nu.png' },
    'NZ': { name: 'New Zealand', flag: 'https://flagcdn.com/w20/nz.png' },
    'OM': { name: 'Oman', flag: 'https://flagcdn.com/w20/om.png' },
    'PA': { name: 'Panama', flag: 'https://flagcdn.com/w20/pa.png' },
    'PE': { name: 'Peru', flag: 'https://flagcdn.com/w20/pe.png' },
    'PF': { name: 'French Polynesia', flag: 'https://flagcdn.com/w20/pf.png' },
    'PG': { name: 'Papua New Guinea', flag: 'https://flagcdn.com/w20/pg.png' },
    'PH': { name: 'Philippines', flag: 'https://flagcdn.com/w20/ph.png' },
    'PK': { name: 'Pakistan', flag: 'https://flagcdn.com/w20/pk.png' },
    'PL': { name: 'Poland', flag: 'https://flagcdn.com/w20/pl.png' },
    'PM': { name: 'Saint Pierre and Miquelon', flag: 'https://flagcdn.com/w20/pm.png' },
    'PN': { name: 'Pitcairn Islands', flag: 'https://flagcdn.com/w20/pn.png' },
    'PR': { name: 'Puerto Rico', flag: 'https://flagcdn.com/w20/pr.png' },
    'PS': { name: 'Palestine', flag: 'https://flagcdn.com/w20/ps.png' },
    'PT': { name: 'Portugal', flag: 'https://flagcdn.com/w20/pt.png' },
    'PW': { name: 'Palau', flag: 'https://flagcdn.com/w20/pw.png' },
    'PY': { name: 'Paraguay', flag: 'https://flagcdn.com/w20/py.png' },
    'QA': { name: 'Qatar', flag: 'https://flagcdn.com/w20/qa.png' },
    'QC': { name: 'Quebec', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Quebec_flag.png' },
    'RE': { name: 'Réunion', flag: 'https://flagcdn.com/w20/re.png' },
    'RO': { name: 'Romania', flag: 'https://flagcdn.com/w20/ro.png' },
    'RS': { name: 'Serbia', flag: 'https://flagcdn.com/w20/rs.png' },
    'RU': { name: 'Russia', flag: 'https://flagcdn.com/w20/ru.png' },
    'RW': { name: 'Rwanda', flag: 'https://flagcdn.com/w20/rw.png' },
    'SA': { name: 'Saudi Arabia', flag: 'https://flagcdn.com/w20/sa.png' },
    'SB': { name: 'Solomon Islands', flag: 'https://flagcdn.com/w20/sb.png' },
    'SC': { name: 'Seychelles', flag: 'https://flagcdn.com/w20/sc.png' },
    'SD': { name: 'Sudan', flag: 'https://flagcdn.com/w20/sd.png' },
    'SE': { name: 'Sweden', flag: 'https://flagcdn.com/w20/se.png' },
    'SG': { name: 'Singapore', flag: 'https://flagcdn.com/w20/sg.png' },
    'SH': { name: 'Saint Helena', flag: 'https://flagcdn.com/w20/sh.png' },
    'SI': { name: 'Slovenia', flag: 'https://flagcdn.com/w20/si.png' },
    'SJ': { name: 'Svalbard and Jan Mayen', flag: 'https://flagcdn.com/w20/sj.png' },
    'SK': { name: 'Slovakia', flag: 'https://flagcdn.com/w20/sk.png' },
    'SL': { name: 'Sierra Leone', flag: 'https://flagcdn.com/w20/sl.png' },
    'SM': { name: 'San Marino', flag: 'https://flagcdn.com/w20/sm.png' },
    'SN': { name: 'Senegal', flag: 'https://flagcdn.com/w20/sn.png' },
    'SO': { name: 'Somalia', flag: 'https://flagcdn.com/w20/so.png' },
    'SR': { name: 'Suriname', flag: 'https://flagcdn.com/w20/sr.png' },
    'SS': { name: 'South Sudan', flag: 'https://flagcdn.com/w20/ss.png' },
    'ST': { name: 'São Tomé and Príncipe', flag: 'https://flagcdn.com/w20/st.png' },
    'SV': { name: 'El Salvador', flag: 'https://flagcdn.com/w20/sv.png' },
    'SX': { name: 'Sint Maarten', flag: 'https://flagcdn.com/w20/sx.png' },
    'SY': { name: 'Syria', flag: 'https://flagcdn.com/w20/sy.png' },
    'SZ': { name: 'Eswatini', flag: 'https://flagcdn.com/w20/sz.png' },
    'TC': { name: 'Turks and Caicos Islands', flag: 'https://flagcdn.com/w20/tc.png' },
    'TD': { name: 'Chad', flag: 'https://flagcdn.com/w20/td.png' },
    'TF': { name: 'French Southern Territories', flag: 'https://flagcdn.com/w20/tf.png' },
    'TG': { name: 'Togo', flag: 'https://flagcdn.com/w20/tg.png' },
    'TH': { name: 'Thailand', flag: 'https://flagcdn.com/w20/th.png' },
    'TJ': { name: 'Tajikistan', flag: 'https://flagcdn.com/w20/tj.png' },
    'TK': { name: 'Tokelau', flag: 'https://flagcdn.com/w20/tk.png' },
    'TL': { name: 'Timor-Leste', flag: 'https://flagcdn.com/w20/tl.png' },
    'TM': { name: 'Turkmenistan', flag: 'https://flagcdn.com/w20/tm.png' },
    'TN': { name: 'Tunisia', flag: 'https://flagcdn.com/w20/tn.png' },
    'TO': { name: 'Tonga', flag: 'https://flagcdn.com/w20/to.png' },
    'TR': { name: 'Turkey', flag: 'https://flagcdn.com/w20/tr.png' },
    'TT': { name: 'Trinidad and Tobago', flag: 'https://flagcdn.com/w20/tt.png' },
    'TV': { name: 'Tuvalu', flag: 'https://flagcdn.com/w20/tv.png' },
    'TW': { name: 'Taiwan', flag: 'https://flagcdn.com/w20/tw.png' },
    'TZ': { name: 'Tanzania', flag: 'https://flagcdn.com/w20/tz.png' },
    'UA': { name: 'Ukraine', flag: 'https://flagcdn.com/w20/ua.png' },
    'UG': { name: 'Uganda', flag: 'https://flagcdn.com/w20/ug.png' },
    'UM': { name: 'United States Minor Outlying Islands', flag: 'https://flagcdn.com/w20/um.png' },
    'US': { name: 'United States', flag: 'https://flagcdn.com/w20/us.png' },
    'UY': { name: 'Uruguay', flag: 'https://flagcdn.com/w20/uy.png' },
    'UZ': { name: 'Uzbekistan', flag: 'https://flagcdn.com/w20/uz.png' },
    'VA': { name: 'Vatican City', flag: 'https://flagcdn.com/w20/va.png' },
    'VC': { name: 'Saint Vincent and the Grenadines', flag: 'https://flagcdn.com/w20/vc.png' },
    'VE': { name: 'Venezuela', flag: 'https://flagcdn.com/w20/ve.png' },
    'VG': { name: 'British Virgin Islands', flag: 'https://flagcdn.com/w20/vg.png' },
    'VI': { name: 'United States Virgin Islands', flag: 'https://flagcdn.com/w20/vi.png' },
    'VN': { name: 'Vietnam', flag: 'https://flagcdn.com/w20/vn.png' },
    'VU': { name: 'Vanuatu', flag: 'https://flagcdn.com/w20/vu.png' },
    'WF': { name: 'Wallis and Futuna', flag: 'https://flagcdn.com/w20/wf.png' },
    'WS': { name: 'Samoa', flag: 'https://flagcdn.com/w20/ws.png' },
    'YE': { name: 'Yemen', flag: 'https://flagcdn.com/w20/ye.png' },
    'YT': { name: 'Mayotte', flag: 'https://flagcdn.com/w20/yt.png' },
    'ZA': { name: 'South Africa', flag: 'https://flagcdn.com/w20/za.png' },
    'ZM': { name: 'Zambia', flag: 'https://flagcdn.com/w20/zm.png' },
    'ZW': { name: 'Zimbabwe', flag: 'https://flagcdn.com/w20/zw.png' }
  };

  isValidCountryCode(): boolean {
    if (!this.countryCode || !this.countryCode.trim()) {
      return false;
    }
    const code = this.countryCode.trim().toUpperCase();
    return !!this.countries[code];
  }

  getCountryFlag(countryCode: string | undefined | null): string {
    const code = countryCode?.trim().toUpperCase();
    return this.countries[code || '']?.flag || '';
  }

  getCountryFlagUrl(countryCode: string | undefined | null): string {
    const code = countryCode?.trim().toUpperCase();
    return this.countries[code || '']?.flag || '';
  }

  getCountryName(countryCode: string | undefined | null): string {
    const code = countryCode?.trim().toUpperCase();
    return this.countries[code || '']?.name || '';
  }
}